let express=require("express")
const { gettask, addtask, updtask, deltask } = require("../controller/taskcont")
const { reg, login } = require("../controller/ucont")
const { getcomptask, addcomptask,delcomptask } = require("../controller/compcont")
let rt=new express.Router()
rt.post("/addtask",addtask)
rt.get("/gettask/:userId",gettask)
rt.put("/updtask",updtask)
rt.delete("/deltask/:idno",deltask)
rt.post("/reg",reg)
rt.post("/login",login)
rt.post("/addcomptask",addcomptask)
rt.get("/getcomptask/:userId",getcomptask)
rt.delete("/delcomptask/:idno",delcomptask)
module.exports=rt